@startuml
'https://plantuml.com/class-diagram
class Test {
    -int countOfQuestions
    -int overallPoints
    -String subject
    -Question[] questions
    +Getter()
    +Setter()
}
class Question {
    -int difficulty
    -int points
    -String questionString
    -String subject
    -String[] keywords
    -String[] topics
    -Boolean language
    -String course
    +Getter()
    +Setter()
}
class Question_open {
    -String answer
    +Getter()
    +Setter()
}
class Question_mc {
    -int countOfAnswers
    -String[] answers
    +Getter()
    +Setter()
}
class Image {
    -int position
    -String path
    -String name
    +Getter()
    +Setter()
}
class Menu {
    +Test makeNewTest()
    +Question addNewQuestion()
    +Question getQuestion(int id)
    +Question[] getAllQuestions(String subject)
    +void editQuestion(Question newQuestion)
    +String selectSubject()
    +void editTestHeader()
}

Menu "1" *-- "0..*" Test : "produce"
Question "0..*" --* "1" Menu : "produce & add"
Test "1..*" o-- "1..*" Question : "has"
Question "1..*" *-- "0..*" Image : has
Question_mc <|-- Question
Question_open <|-- Question

@enduml